[package]
name = "circuits"
type = "bin"
authors = [""]

[dependencies]
bignum = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir-bignum" }
zkemail = { tag = "v0.4.2", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
sha256 = { git = "https://github.com/noir-lang/sha256", tag = "v0.1.2" }
